"use client";

import React, { useState } from "react";
import {
  FileText,
  Download,
  CheckCircle2,
  BrainCircuit,
  Split,
  TrendingUp,
  AlertCircle,
  ArrowRight,
  Shield,
  Layers,
} from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";
import { GlassCard } from "@/components/ui/GlassCard";
import { CyberBadge } from "@/components/ui/CyberBadge";
import { MOCK_SHAP_FACTORS } from "@/lib/mockData";

export const CaseDeepDive: React.FC = () => {
  const [downloading, setDownloading] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleDownload65B = () => {
    setDownloading(true);
    setTimeout(() => {
      setDownloading(false);
      setDownloadSuccess(true);
      const certificateContent = `
================================================================================
  CERTIFICATE UNDER SECTION 65B OF THE INDIAN EVIDENCE ACT, 1872 /
  SECTION 63 OF THE BHARATIYA SAKSHYA ADHINIYAM (BSA), 2023
================================================================================
Generated by: PRATYAKSH Cybercrime Interdiction Platform (SIH-26184)
Issuing Authority: Indian Cyber Crime Coordination Centre (I4C), MHA, New Delhi
Date/Time of Generation: ${new Date().toISOString()}

1. CASE DETAILS:
   - Complaint Ticket ID: 1930-PUN-2026-8812
   - Incident Classification: Digital Arrest & Financial Siphoning
   - Defrauded Amount: INR 3,50,000/-
   - Complainant: Dr. Arvind S. Kulkarni (Pune, Maharashtra)

2. MULTI-HOP MONEY ROUTING AUDIT (MULE TRAIL):
   - Layer 0 (Victim): Dr. Arvind K. -> Account Ref: A/C #XXXX9012
   - Layer 1 (Mule): Ramesh K. -> ICICI Bank A/C #XXXX4421 (Transferred: INR 3,50,000)
   - Layer 2 (Fan-Out Smurfing):
       Branch A: Sunil B. (Axis Bank) -> INR 1,20,000
       Branch B: Manoj V. (SBI Bank)  -> INR 1,50,000 [Targeted for Physical Cash-Out]
       Branch C: Vijay P. (Kotak Bank)-> INR 80,000

3. AI INTERDICTION PREDICTION & EVIDENCE:
   - Target Predicted Hotspot: SBI ATM — VIT College Gate, Bibwewadi (18.4650, 73.8690)
   - Risk Assessment Score: 82% Probability of Physical Withdrawal
   - Estimated Time Window: 8 - 25 Minutes
   - XGBoost Feature Weights: Proximity (40%), Transit Funnel (30%), Gang Modus (20%), Kiosk Type (10%)

4. BLOCKCHAIN IMMUTABILITY & HASH INTEGRITY:
   - Section 65B SHA-256 Hash: 0x8fa3d209ec1b45920b784a91901c4598d1a082bc34091eac9810ef324901cb4e
   - Anchored on Consortium Block: #1041 (MHA-I4C Private Subnet)
   - Smart Contract Lien Event: Block #1042 (Tx: 0x9b3fe82a041cb88147d332901a88c2f1092a019b)
================================================================================
      `;

      const blob = new Blob([certificateContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "PRATYAKSH_SECTION_65B_CERTIFICATE_#26184-PUN.txt";
      a.click();
      URL.revokeObjectURL(url);
    }, 1200);
  };

  const chartData = [
    { name: "Proximity to IP Signal", weight: 40, color: "#2563EB" },
    { name: "Transit Travel Time", weight: 30, color: "#0284C7" },
    { name: "Historical Gang Prior", weight: 20, color: "#D97706" },
    { name: "Kiosk Isolation", weight: 10, color: "#64748B" },
  ];

  return (
    <div className="flex flex-col gap-5">
      {/* Top Banner (Editorial Header) */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-white p-4 rounded-lg border border-slate-200 shadow-card">
        <div>
          <div className="flex items-center gap-2">
            <BrainCircuit className="w-5 h-5 text-blue-600" />
            <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide">
              Case Deep-Dive &bull; AI Explainability & Multi-Hop Money Trail
            </h2>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Cryptographic tracing of fan-out mule routing, mathematical SHAP feature contribution, and Section 65B legal admissibility.
          </p>
        </div>

        {/* Section 65B Document Export (Clean Navy CTA) */}
        <button
          onClick={handleDownload65B}
          disabled={downloading}
          className="flex items-center gap-2 px-3.5 py-2 rounded-md text-xs font-semibold tracking-wide bg-slate-900 hover:bg-slate-800 text-white shadow-sm transition-all cursor-pointer disabled:opacity-50"
        >
          {downloadSuccess ? (
            <>
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Section 65B Certificate Exported</span>
            </>
          ) : downloading ? (
            <>
              <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              <span>Generating Certified Record...</span>
            </>
          ) : (
            <>
              <FileText className="w-4 h-4 text-slate-300" />
              <span>Download Section 65B Evidence Certificate</span>
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        {/* LEFT (7 cols) — Multi-Hop Fan-Out Smurfing Graph with Curved SVG Connectors */}
        <div className="lg:col-span-7 flex flex-col gap-4">
          <GlassCard className="p-5 flex flex-col gap-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center gap-2">
                <Split className="w-4 h-4 text-blue-600" />
                <h3 className="text-xs font-bold uppercase tracking-wide text-slate-900">
                  Multi-Hop Mule Routing & Smurfing Graph
                </h3>
              </div>
              <span className="text-[10px] font-mono font-semibold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                FAN-OUT DETECTED (&gt; ₹2,00,000)
              </span>
            </div>

            <p className="text-xs text-slate-500">
              When siphoned funds exceed ₹2,00,000, syndicates fragment transactions across secondary mule accounts to bypass single-card daily ATM limits.
            </p>

            {/* Clean Curved SVG Flow Graph */}
            <div className="relative w-full rounded-lg bg-slate-50/60 border border-slate-200/90 p-5 overflow-x-auto">
              <div className="min-w-[620px] flex items-center justify-between gap-2 relative py-4">
                {/* Node 1: Victim */}
                <div className="flex flex-col items-center gap-1.5 z-10">
                  <div className="w-11 h-11 rounded-lg bg-white border border-slate-300 flex items-center justify-center text-slate-700 shadow-sm">
                    <span className="font-mono text-xs font-bold">L0</span>
                  </div>
                  <div className="text-center">
                    <div className="text-xs font-bold text-slate-900">Victim Account</div>
                    <div className="text-[10px] text-slate-500">Dr. Arvind K.</div>
                    <div className="text-[11px] font-mono text-slate-900 font-bold mt-0.5">₹3,50,000</div>
                  </div>
                </div>

                {/* Curved SVG Connector 1 */}
                <div className="flex-1 flex flex-col items-center px-1">
                  <svg className="w-full h-8 overflow-visible" viewBox="0 0 100 20" preserveAspectRatio="none">
                    <path
                      d="M 0,10 C 40,10 60,10 100,10"
                      fill="none"
                      stroke="#94A3B8"
                      strokeWidth="2"
                      strokeDasharray="4 3"
                    />
                  </svg>
                  <span className="text-[9px] font-mono text-slate-500 font-medium">IMPS &bull; 32s</span>
                </div>

                {/* Node 2: Layer 1 Mule */}
                <div className="flex flex-col items-center gap-1.5 z-10">
                  <div className="w-11 h-11 rounded-lg bg-rose-50 border border-rose-300 flex items-center justify-center text-rose-700 shadow-sm">
                    <span className="font-mono text-xs font-bold">L1</span>
                  </div>
                  <div className="text-center">
                    <div className="text-xs font-bold text-slate-900">Primary Mule</div>
                    <div className="text-[10px] text-slate-500">Ramesh K. (ICICI)</div>
                    <div className="text-[11px] font-mono text-rose-700 font-bold mt-0.5">₹3,50,000 In</div>
                  </div>
                </div>

                {/* Curved SVG Connector 2 (Fan-Out) */}
                <div className="flex-1 flex flex-col items-center px-1">
                  <svg className="w-full h-16 overflow-visible" viewBox="0 0 100 60" preserveAspectRatio="none">
                    <path d="M 0,30 C 40,30 60,10 100,10" fill="none" stroke="#CBD5E1" strokeWidth="1.5" />
                    <path d="M 0,30 C 40,30 60,30 100,30" fill="none" stroke="#2563EB" strokeWidth="2" strokeDasharray="4 3" />
                    <path d="M 0,30 C 40,30 60,50 100,50" fill="none" stroke="#CBD5E1" strokeWidth="1.5" />
                  </svg>
                  <span className="text-[9px] font-mono text-blue-700 font-semibold">3-Way Smurf</span>
                </div>

                {/* Node 3: Fan-Out Accounts */}
                <div className="flex flex-col gap-2 z-10">
                  <div className="flex items-center justify-between gap-3 px-2.5 py-1.5 rounded-md bg-white border border-slate-200 text-[10px] font-mono shadow-xs">
                    <span className="text-slate-600">Branch A (Axis):</span>
                    <span className="text-slate-900 font-bold">₹1,20,000</span>
                  </div>

                  <div className="flex items-center justify-between gap-3 px-2.5 py-1.5 rounded-md bg-blue-50 border border-blue-300 text-[11px] font-mono shadow-xs">
                    <span className="text-blue-800 font-bold">Branch B (SBI) &bull; TARGET:</span>
                    <span className="text-blue-900 font-extrabold">₹1,50,000 &rarr;</span>
                  </div>

                  <div className="flex items-center justify-between gap-3 px-2.5 py-1.5 rounded-md bg-white border border-slate-200 text-[10px] font-mono shadow-xs">
                    <span className="text-slate-600">Branch C (Kotak):</span>
                    <span className="text-slate-900 font-bold">₹80,000</span>
                  </div>
                </div>

                {/* Connector 3 */}
                <div className="flex-1 flex flex-col items-center px-1">
                  <svg className="w-full h-8 overflow-visible" viewBox="0 0 100 20" preserveAspectRatio="none">
                    <path
                      d="M 0,10 C 40,10 60,10 100,10"
                      fill="none"
                      stroke="#E11D48"
                      strokeWidth="2"
                      strokeDasharray="4 3"
                    />
                  </svg>
                  <span className="text-[9px] font-mono text-rose-700 font-semibold">Physical Cash-Out</span>
                </div>

                {/* Node 4: Target ATM Hotspot */}
                <div className="flex flex-col items-center gap-1.5 z-10">
                  <div className="w-12 h-12 rounded-lg bg-rose-50 border-2 border-rose-500 flex flex-col items-center justify-center text-rose-700 shadow-md">
                    <span className="font-mono text-[10px] font-bold">ATM #1</span>
                    <span className="text-[9px] font-mono text-rose-900 font-extrabold">82% RISK</span>
                  </div>
                  <div className="text-center">
                    <div className="text-xs font-bold text-slate-900">SBI ATM Kiosk</div>
                    <div className="text-[10px] text-slate-500">VIT College Gate</div>
                    <div className="text-[10px] font-mono text-blue-700 font-semibold mt-0.5">ETA: 8 mins</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Pattern Explanation Callout */}
            <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-700 flex items-start gap-2.5">
              <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
              <div>
                <b className="text-slate-900">Mule Smurfing Rationale:</b>
                <p className="mt-1 text-slate-600 leading-relaxed">
                  Branch B account card (#XXXX9102) was pinged near the cellular BTS tower covering the Bibwewadi corridor at 10:05:40 IST. The AI flagged this specific branch for physical ATM extraction due to active proximity and transit time alignment.
                </p>
              </div>
            </div>
          </GlassCard>
        </div>

        {/* RIGHT (5 cols) — Minimalist SHAP Bar Charts */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          <GlassCard className="p-5 flex flex-col gap-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-blue-600" />
                <h3 className="text-xs font-bold uppercase tracking-wide text-slate-900">
                  AI Feature Importance (SHAP Explainability)
                </h3>
              </div>
              <span className="text-[10px] font-mono font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                XGBOOST MODEL
              </span>
            </div>

            <p className="text-xs text-slate-500">
              Mathematical weights computed by the 2-stage spatial ranker explaining feature contribution for <b>Rank-1 ATM priority</b>:
            </p>

            {/* Minimalist Horizontal Bar Chart */}
            <div className="h-[210px] w-full pt-1">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={chartData}
                  layout="vertical"
                  margin={{ top: 5, right: 40, left: 10, bottom: 5 }}
                >
                  <XAxis type="number" domain={[0, 50]} unit="%" tick={{ fill: "#64748B", fontSize: 11 }} />
                  <YAxis type="category" dataKey="name" width={120} tick={{ fill: "#334155", fontSize: 11 }} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "#FFFFFF",
                      borderColor: "#E2E8F0",
                      color: "#0F172A",
                      fontSize: "12px",
                      borderRadius: "6px",
                      boxShadow: "0 2px 4px rgba(0,0,0,0.06)",
                    }}
                    formatter={(val) => [`${val}% Contribution`, "Feature Weight"]}
                  />
                  <Bar dataKey="weight" radius={[0, 4, 4, 0]}>
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Feature Breakdown Table */}
            <div className="flex flex-col gap-2 pt-2 border-t border-slate-100">
              {MOCK_SHAP_FACTORS.map((factor, idx) => (
                <div
                  key={idx}
                  className="p-2.5 rounded-md bg-slate-50 border border-slate-200/80 flex items-center justify-between text-xs"
                >
                  <div>
                    <div className="font-semibold text-slate-800">{factor.feature}</div>
                    <div className="text-[10px] text-blue-700 font-mono mt-0.5">{factor.impact}</div>
                  </div>
                  <div className="text-right font-mono">
                    <div className="font-bold text-slate-900">{factor.weight}% Weight</div>
                    <div className="text-[10px] text-slate-500">{factor.rawValue}</div>
                  </div>
                </div>
              ))}
            </div>
          </GlassCard>
        </div>
      </div>
    </div>
  );
};
